language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: DHYiSfgk0xCX7gxR6zNvuWTfgrf6jethNdt8E9mh0aquROKJX4uAcKmPuaGgdjSHh3qv1rou9E1BG7kgGWKFaVnfjatbhZelTEefpziOgtMeWCz9KKsMdhRY7lzq7fKR4J5ZAQ+jD0QQ6TQm6SeyGw+b4yko+H3gsMoIY4ed6N/+BQOwCSwRamTperGe1oVQkJ2UMqOzxs7R8PAwJl5NTvbRwPrUyJQ1Q38tpYC/dwyh8lFEbAtniE1Tg1AZ4xVWDasVITvFZ+D7KRcGdnM8iMiH+2OqWCJmo6z/5eHBCZXGRxBKymz0rZfX5TrE1p1NO5LJp3PxkA0dr7+1zzKQC4ttJzMpOKaJPeaFuiF79Df4+kv/GTQyNGF/gZHj9kbuW3Ey5neGB8LJDekiXDDUwMNc7cEJo9owB3oavsXt3G5965vpDJn/Ac4xbeDFCR0ACZEB4nAIRe9vhOU9rZF35N6ETdj3+p779dtTUAntmq4asr9iDBr4xgEd3fYCLfdPx/wjrxTmZ743K0rlU1RVyyp0KYc8tseWhEdCC0zRyJZHgwn8WgzLTA/tX60AYx92p/rbw429oFE5FdDW8GbXlcwKkPIg7rlTTEga5fLFdLXGnn5q4HiDPlccXObIym9CKb+3YVK86R/SxGnToBjCfG456bUQPF/5begOOmb87lI=
  app: megan-noteful-v3
  on:
    repo: thinkful-ei19/megan-noteful-v3
